### ISSUE TITLE
Nested Packets

### ISSUE THREAD

**Issue by BataGPT** [Nundir/photon-packet-parser#2]
The current parser handles the deserialization of top-level objects effectively. However, when encountering nested objects within the data, it only deserializes the first layer. Subsequent nested layers remain as buffers, making it difficult to work with the complete data structure.

Example:

// Expected Output (Fully Deserialized)
{
    "name": "John Doe",
    "address": {
        "street": "123 Main St",
        "city": "Anytown"
    }
}

// Actual Output (Partial Deserialization)
{
    "name": "John Doe",
    "address": <Buffer ...> 
}

Real Example: 

![image](https://github.com/user-attachments/assets/cbe1e4a7-f993-4e8d-af69-bf9d3ac77e79)

Impact:

This limitation hinders the usability of the parser for data formats that rely heavily on nested structures. I'm currently working on a project where nested object support is essential, and it would be incredibly helpful if this functionality could be added.

Request:
Any one help on how to handle nested buffers

**Comment by 0xN0x** [comment]
I'm not sure to understand clearly the issue, in you screenshot the data are buffer because it seem to be some bytearray in your serialized data, not dictionaries

Nested object are supported with the ObjectArray and Dictionary type by the protocol16 of Photon Engine and should be well deserialized by this parser

ObjectArray don't seem to be used in your example, do you have an example with the data serialized and deserialized and how it should have been deserialized ?
